In [2]:
import re
import pandas as pd
import numpy as np

df = pd.read_csv("GSAF5.csv", encoding="ISO-8859-1")
df
#(encoding="ISO-8859-1") = encodes what it refers to as "Latin alphabet no. 1", consisting of 
#191 characters from the Latin script. This character-encoding scheme is used throughout the Americas,
#Western Europe, Oceania, and much of Africa. It is also commonly used in most standard romanizations 
#of East-Asian languages. With this encode we are able to read this and many other files.

,Case Number,Date,Year,Type,Country,Area,Location,Activity,Name,Sex,...,Species,Investigator or Source,pdf,href formula,href,Case Number.1,Case Number.2,original order,Unnamed: 22,Unnamed: 23
0,2016.09.18.c,18-Sep-16,2016,Unprovoked,USA,Florida,"New Smyrna Beach, Volusia County",Surfing,male,M,...,NaN,"Orlando Sentinel, 9/19/2016",2016.09.18.c-NSB.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2016.09.18.c,2016.09.18.c,5993,NaN,NaN
1,2016.09.18.b,18-Sep-16,2016,Unprovoked,USA,Florida,"New Smyrna Beach, Volusia County",Surfing,Chucky Luciano,M,...,NaN,"Orlando Sentinel, 9/19/2016",2016.09.18.b-Luciano.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2016.09.18.b,2016.09.18.b,5992,NaN,NaN
2,2016.09.18.a,18-Sep-16,2016,Unprovoked,USA,Florida,"New Smyrna Beach, Volusia County",Surfing,male,M,...,NaN,"Orlando Sentinel, 9/19/2016",2016.09.18.a-NSB.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2016.09.18.a,2016.09.18.a,5991,NaN,NaN
3,2016.09.17,17-Sep-16,2016,Unprovoked,AUSTRALIA,Victoria,Thirteenth Beach,Surfing,Rory Angiolella,M,...,NaN,"The Age, 9/18/2016",2016.09.17-Angiolella.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2016.09.17,2016.09.17,5990,NaN,NaN
4,2016.09.15,16-Sep-16,2016,Unprovoked,AUSTRALIA,Victoria,Bells Beach,Surfing,male,M,...,2 m shark,"The Age, 9/16/2016",2016.09.16-BellsBeach.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2016.09.16,2016.09.15,5989,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5987,ND.0005,Before 1903,0,Unprovoked,AUSTRALIA,Western Australia,Roebuck Bay,Diving,male,M,...,NaN,"H. Taunton; N. Bartlett, p. 234",ND-0005-RoebuckBay.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,ND.0005,ND.0005,6,NaN,NaN
5988,ND.0004,Before 1903,0,Unprovoked,AUSTRALIA,Western Australia,NaN,Pearl diving,Ahmun,M,...,NaN,"H. Taunton; N. Bartlett, pp. 233-234",ND-0004-Ahmun.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,ND.0004,ND.0004,5,NaN,NaN
5989,ND.0003,1900-1905,0,Unprovoked,USA,North Carolina,Ocracoke Inlet,Swimming,Coast Guard personnel,M,...,NaN,"F. Schwartz, p.23; C. Creswell, GSAF",ND-0003-Ocracoke_1900-1905.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,ND.0003,ND.0003,4,NaN,NaN
5990,ND.0002,1883-1889,0,Unprovoked,PANAMA,NaN,"Panama Bay 8ºN, 79ºW",NaN,Jules Patterson,M,...,NaN,"The Sun, 10/20/1938",ND-0002-JulesPatterson.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,ND.0002,ND.0002,3,NaN,NaN
5991,ND.0001,1845-1853,0,Unprovoked,CEYLON (SRI LANKA),Eastern Province,"Below the English fort, Trincomalee",Swimming,male,M,...,NaN,S.W. Baker,ND-0001-Ceylon.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,ND.0001,ND.0001,2,NaN,NaN

In [3]:
#thinking about our hypothesis where we will try to demonstrate that shark's attacks on human 
#beings are increasing because humans invade their habitat more and more for different reasons.

#first we will start by cleaning our data and get from it the most important we think we will need
#for our investigation.

#Creating new DataFrame without duplicated columns or innecesary for our investigation:
dfa = df.drop(columns=["Case Number", "pdf", "href formula", "href", "Case Number.1", "Case Number.2",
                       "Unnamed: 22", "Unnamed: 23"])

#rearranging DataFrame:
#change columns order:
cols=list(dfa.columns.values)
dfa = dfa[[cols[-1]] + cols[0:-1]]

#change column Name:
x = {"original order":"Case Number"}
dfa = dfa.rename(columns=x)

#define specific data to work on our hypothesis:
dfa.loc[dfa["Type"]=="Boat", "Type"] = "Unprovoked"
dfa.loc[dfa["Type"]=="Boating", "Type"] = "Unprovoked"
dfa.loc[dfa["Type"]=="Sea Disaster", "Type"] = "Provoked"
dfa.loc[dfa["Type"]=="Invalid", "Type"] = "Unknown"
dfa.loc[dfa["Type"]==" ", "Type"] = "Unknown"
dfa.loc[dfa["Type"]=="NaN", "Type"] = "Unknown"
dfa.loc[dfa["Name"]=="male", "Name"] = "Unknown"
dfa.loc[dfa["Name"]=="female", "Name"] = "Unknown"
dfa.loc[dfa["Name"]=="boy", "Name"] = "Unknown"
dfa.loc[dfa["Name"]==" ", "Name"] = "Unknown"
dfa.loc[dfa["Name"]=="NaN", "Name"] = "Unknown"
dfa.loc[dfa["Activity"]==" ", "Activity"] = "Unknown"
dfa.loc[dfa["Activity"]=="NaN", "Activity"] = "Unknown"
dfa.loc[dfa["Case Number"]==" ", "Case Number"] = "Unknown"
dfa.loc[dfa["Case Number"]=="NaN", "Case Number"] = "Unknown"
dfa.loc[dfa["Date"]==" ", "Date"] = "Unknown"
dfa.loc[dfa["Date"]=="NaN", "Date"] = "Unknown"
dfa.loc[dfa["Year"]==" ", "Year"] = "Unknown"
dfa.loc[dfa["Year"]=="NaN", "Year"] = "Unknown"
dfa.loc[dfa["Country"]==" ", "Country"] = "Unknown"
dfa.loc[dfa["Country"]=="NaN", "Country"] = "Unknown"
dfa.loc[dfa["Area"]==" ", "Area"] = "Unknown"
dfa.loc[dfa["Area"]=="NaN", "Area"] = "Unknown"
dfa.loc[dfa["Location"]==" ", "Location"] = "Unknown"
dfa.loc[dfa["Location"]=="NaN", "Location"] = "Unknown"
#dfa.loc[dfa["Sex"]==" ", "Sex"] = "Unknown"
dfa.loc[dfa["Age"]==" ", "Age"] = "Unknown"
dfa.loc[dfa["Age"]=="NaN", "Age"] = "Unknown"
dfa.loc[dfa["Injury"]==" ", "Injury"] = "Unknown"
dfa.loc[dfa["Injury"]=="NaN", "Injury"] = "Unknown"
dfa.loc[dfa["Fatal (Y/N)"]==" ", "Fatal (Y/N)"] = "Unknown"
dfa.loc[dfa["Fatal (Y/N)"]=="NaN", "Fatal (Y/N)"] = "Unknown"
dfa.loc[dfa["Time"]=="NaN", "Time"] = "Unknown"
dfa.loc[dfa["Time"]==" ", "Time"] = "Unknown"
#dfa.loc[dfa["Species"]=="NaN", "Species"] = "Unknown"
dfa.loc[dfa["Investigator or Source"]==" ", "Investigator or Source"] = "Unknown"
dfa.loc[dfa["Investigator or Source"]=="NaN", "Investigator or Source"] = "Unknown"



#

dfa.groupby(["Type"]).mean().sort_values("Year", ascending=False)

C:\Users\Lojo\Anaconda3\lib\site-packages\pandas\core\ops\__init__.py:1115: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  result = method(y)

            Case Number         Year
Type
Unknown     2837.283237  1952.616570
Provoked    2615.752896  1928.371943
Unprovoked  3078.433348  1921.650980

In [ ]:
dfa.to_csv("", index=False)